'''
    Problem 2:
    Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    https://projecteuler.net/problem=2
'''

max = 4000000
sum = 2
first_number = 1
second_number = 2
while first_number < max and second_number < max:
    if first_number < second_number:
        first_number += second_number
        if first_number % 2 == 0:
            sum += first_number
    else:
        second_number += first_number
        if second_number % 2 == 0:
            sum += second_number

print sum
